wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25] # 12 (Left)
    rows: [5, 10, 10, 4, 25, 90] # 6 (Top)
  refreshInterval: 1
  mods:
    # clocks_b:
    #   colors:
    #     rows:
    #       even: "lightblue"
    #       odd: "white"
    #   enabled: true
    #   locations:
    #     Paris: "Europe/Paris"
    #     Barcelona: "Europe/Madrid"
    #     Dubai: "Asia/Dubai"
    #   position:
    #     top: 0
    #     left: 2
    #     height: 1
    #     width: 1
    #   refreshInterval: 15
    #   sort: "alphabetical"
    #   title: "Clocks B"
    #   type: "clocks"
    # feedreader:
    #   enabled: true
    #   feeds:
    #   - http://wtfutil.com/blog/index.xml
    #   feedLimit: 10
    #   position:
    #     top: 1
    #     left: 1
    #     width: 2
    #     height: 1
    #   updateInterval: 14400
    # docker:
    #   type: docker
    #   enabled: true
    #   labelColor: lightblue
    #   position:
    #     top: 2
    #     left: 2
    #     height: 1
    #     width: 1
    #   refreshInterval: 1
    uptime:
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 2
      refreshInterval: 30
      type: cmdrunner
    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 1
      showCPU: true
      showMem: true
      showSwp: true
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 2
      refreshInterval: 150
    pihole:
      apiUrl: 
      enabled: true
      maxClientWidth: 20
      maxDomainWidth: 20
      position:
        top: 0
        left: 7
        height: 3
        width: 4
      refreshInterval: 60
      showSummary: true
      showTopItems: 5
      showTopClients: 5
      token: 
